query GetOneBoardByUri($uri: String) {
  getOneBoard(uri: $uri) {
    id
    name
    uri
    createdAt
    updatedAt
    columns {
      count
      nodes {
        id
        name
        columnColor
        tasks {
          count
          nodes {
            id
            title
            description
            subtasks {
              completedSubtasks
              count
              nodes {
                id
                title
                completed
              }
            }
          }
        }
      }
    }
  }
}
